---
abstract: 'Alien for chromaprint'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  Test2::V0: '0.000060'
  Test::Alien: '0'
  perl: '5.008001'
configure_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  Alien::Build::Plugin::Build::CMake: '0.99'
  ExtUtils::MakeMaker: '6.52'
  perl: '5.008001'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-chromaprint
requires:
  Alien::Base: '0.038'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/plicease/Alien-chromaprint/issues
  homepage: https://metacpan.org/pod/Alien::chromaprint
  repository: git://github.com/plicease/Alien-chromaprint.git
version: '0.02'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.28'
  requires:
    share:
      Alien::cmake3: '0.02'
      Archive::Tar: '0'
      Config: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_use_unsafe_inc: 0
